### ISSUE TITLE
What types of variants can RNAIndel call?

### ISSUE THREAD

**Issue by FrankFeng** [stjude/RNAIndel#20]
Besides INDELs, can RNAIndel call other types of variants? Especially, can RNAIndel call inversion and delin (the combined deletion-insertion)? Thanks!

**Comment by rawagiha** [comment]
RNAIndel can call complex indels, wherein deletion and insertion co-occur. I think this is what you mean by delin. I am sorry that RNAIndel does not support for inversions as this is considered structual variant rather than indel. Please let me know if you have further questions.
