### ISSUE TITLE
Failed to open FASTA file

### ISSUE THREAD

**Issue by altintasali** [stjude/RNAIndel#43]
Dear authors,

Thanks a lot for this fantastic tool. I followed your recommendations for running the tool, however, I keep getting errors related to FASTA file reading. I was wondering if you can help me to solve the issue. I elaborated on the details below. Thanks a lot for your help in advance. 

### Preparation

1. Run `STAR` with 2-pass
2. Run `gatk MarkDuplicates`. The output `mybam.sorted.markdup.bam` is generated.
3. Install `RNAindel` using `pip`
4. Download and extract the [data package for GRCh38](https://zenodo.org/record/6109305/files/data_dir_grch38.tar.gz) tarball.
5. Download the same [FASTA file](https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_44/GRCh38.primary_assembly.genome.fa.gz) used for generating the STAR index.
6. `gunzip` and index (`samtools faidx`) the FASTA file

### The problem

When I run the following code on MacOS (M1-chip):
```
$ rnaindel PredictIndels \
    -i mybam.sorted.markdup.bam \
    -o output.vcf \
    -r GRCh38.primary_assembly.genome.fa \
    -d data_dir_grch38
```

I received the warning below and the program keeps hanging (over 1-hour for now):
```
[E::fai_load3_core] Failed to open FASTA file GRCh38.primary_assembly.genome.fa
```

I followed the same steps on a Linux machine, but I received an error message:

```
Traceback (most recent call last):
  File "/home/people/${USER}/.local/bin/rnaindel", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/people/${USER}/.local/lib/python3.11/site-packages/rnaindel/rnaindel.py", line 12, in main
    Commands()
  File "/home/people/${USER}/.local/lib/python3.11/site-packages/rnaindel/rnaindel.py", line 44, in __init__
    getattr(self, args.subcommand)()
  File "/home/people/${USER}/.local/lib/python3.11/site-packages/rnaindel/rnaindel.py", line 47, in PredictIndels
    ra.analyze("PredictIndels", version=__version__)
  File "/home/people/${USER}/.local/lib/python3.11/site-packages/rnaindel/analysis/analyzer.py", line 58, in analyze
    df = classify(df, "{}/models".format(data_dir), n_processes)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/people/${USER}/.local/lib/python3.11/site-packages/rnaindel/analysis/classifier.py", line 22, in classify
    df = calculate_proba(df, model_dir, num_of_processes)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/people/${USER}/.local/lib/python3.11/site-packages/rnaindel/analysis/classifier.py", line 59, in calculate_proba
    [
  File "/home/people/${USER}/.local/lib/python3.11/site-packages/rnaindel/analysis/classifier.py", line 60, in <listcomp>
    predict(model, data=df_sni, features=sni_features)
  File "/home/people/${USER}/.local/lib/python3.11/site-packages/rnaindel/analysis/classifier.py", line 144, in predict
    rf = pickle.load(model_pkl)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "sklearn/tree/_tree.pyx", line 728, in sklearn.tree._tree.Tree.__setstate__
  File "sklearn/tree/_tree.pyx", line 1432, in sklearn.tree._tree._check_node_ndarray
ValueError: node array from the pickle has an incompatible dtype:
- expected: {'names': ['left_child', 'right_child', 'feature', 'threshold', 'impurity', 'n_node_samples', 'weighted_n_node_samples', 'missing_go_to_left'], 'formats': ['<i8', '<i8', '<i8', '<f8', '<f8', '<i8', '<f8', 'u1'], 'offsets': [0, 8, 16, 24, 32, 40, 48, 56], 'itemsize': 64}
- got     : [('left_child', '<i8'), ('right_child', '<i8'), ('feature', '<i8'), ('threshold', '<f8'), ('impurity', '<f8'), ('n_node_samples', '<i8'), ('weighted_n_node_samples', '<f8')]
```

**Comment by rawagiha** [comment]
@altintasali Thanks a lot for this detailed report. About the error on your Linux machine, would you please check the sklearn version? This problem may be related to [https://stackoverflow.com/questions/76612971/serialized-machine-learning-model-pickle-on-streamlit-web-app-throws-an-error](url). If your version is > 1.3, please try a lower version.  

Also, the docker version won't help you? 

About the FASTA file error, we try to replicate your problem. May take some time to resolve this.

**Comment by rawagiha** [comment]
@altintasali  I was able to replicate the error on Linux. As suspected, it is due to the version conflict. sklearn > 1.3 does not deserialize the pre-trained model. 

First, please do:
`pip install scikit-learn==1.2.2`

Then run your RNAIndel command.

**Comment by rawagiha** [comment]
@altintasali 
We have introduced [SetUp](https://github.com/stjude/RNAIndel#set-up) so that you can run without changing your sklearn version.

1. Install version 3.3.1 (just uploaded) 
    `pip install rnaindel`  
2. Download the new data package
     `curl -LO https://zenodo.org/records/10035247/files/data_dir_grch38.tar.gz `
      `tar -zxf data_dir_grch38.v3.tar.gz`
3.  Run SetUp. This is only needed once (first-time only).
    `rnaindel SetUp -d data_dir_grch38` 
4.  Run RNAIndel. 
    `rnaindel PredictIndels -i ...`

Step 3 "SetUp" is not necessary when you run RNAIndel next time. 
This will solve the problem you had on Linux.

About the error on M1, we were not able to replicate it (the tool ran successfully on our testing).

**Comment by altintasali** [comment]
Dear @rawagiha,

Thank you so much for your prompt responses and kind help with the issue. I confirm that downgrading the `scikit-learn` to `version 1.2.2` solved the issues for both partially *MacOS/M1* and *Linux*. 

I believe the issue on *MacOS/M1* is due to parallelization. When I tried `rnaindel PredictIndels` with 1 core, it was functional: 
```
$ rnaindel PredictIndels \
    -i mybam.sorted.markdup.bam \
    -o output.vcf \
    -r GRCh38.primary_assembly.genome.fa \
    -d data_dir_grch38 \
    -p 1
```

However, increasing setting `-p` to `>1` still causes the same issue on *MacOS/M1*:

```
$ rnaindel PredictIndels \
    -i mybam.sorted.markdup.bam \
    -o output.vcf \
    -r GRCh38.primary_assembly.genome.fa \
    -d data_dir_grch38 \
    -p 1

[E::fai_load3_core] Failed to open FASTA file GRCh38.primary_assembly.genome.fa
```

I haven't tried `rnaindel` version 3.3.1 yet. I will give it a try on MacOS/M1 again and will update my post.

**Comment by rawagiha** [comment]
@altintasali Thanks a lot for the additional info.
For the parallelization problem, please append  `--safety-mode` to your command.

**Comment by altintasali** [comment]
Many thanks @rawagiha. `--safety-mode` solved the parallelization problem on *MacOS/M1*.

As an improvement, can `--safety-mode` be the default on *MacOS/M1* in the future version?

**Comment by rawagiha** [comment]
@altintasali We would consider your suggestion in a future release. We also appreciate your interest in the tool.
