### ISSUE TITLE
I get different results with the v2 version and the v3 version

### ISSUE THREAD

**Issue by JeWeizhong** [stjude/RNAIndel#49]
Hi, I am analyzing indel with two separate versions of the same sample, but I get different results.

This is the result of version v2.2.4.
![image](https://github.com/stjude/RNAIndel/assets/29620633/df2ce171-4ca1-4252-8798-8a487c5afaab)

This is the result of version v3.3.3.
![image](https://github.com/stjude/RNAIndel/assets/29620633/901697e9-ceb4-4372-8b22-b0ab66795838)

This is the result of IGV.
![image](https://github.com/stjude/RNAIndel/assets/29620633/27198d5a-845e-4dd4-9b0b-e361a7730ae9)

Isn't it possible that the results of the V3 version are wrong?

thanks.

**Comment by rawagiha** [comment]
@JeWeizhong, this appears a regression with version 3. Thanks a lot for reporting this. 
Is it possible for you to share a slice of the BAM? A sliced BAM file can be made:
`samtools view -b your_bam_file "chr6:152599000-152599500" > sliced.bam` 

I am grateful if you can email the sliced BAM for debugging.

**Comment by JeWeizhong** [comment]
Sorry, I didn't find your email address, I shared the file on Google Drive.

https://drive.google.com/file/d/1421Tj5YZglLlJzXUF1Iade_kdG-WN46E/view?usp=sharing

**Comment by rawagiha** [comment]
Received it. Thanks a lot for your help. I will get back to you once I have checked the issue. 

My contact was [here](https://github.com/stjude/RNAIndel#contact)

**Comment by rawagiha** [comment]
The issue was due to an error in [indelPost](https://github.com/stjude/indelPost). RNAIndel v3 relies on indelPost for indel realignment.

I have released a fixed version as indelPost version 0.2.2.  On a test using your example, RNAIndel v3 gives the "CTG" insertion at 152599223.

Please update your copy of indelPost to this version. If you are using the Docker version, please allow one or two more days for deployment.

**Comment by rawagiha** [comment]
Thanks again about this. Indeed, `repeat` should be `=1` with V3.

My apologies. I forgot to update a part in indelPost related to the previous fix. As you might already be aware, this indel is near splice site. indelPost does a special treatment for indels around splice sites.

The updated source code is already [here](https://github.com/stjude/indelPost/tree/master). 
I confirmed that we have `repeat=1` as expected. 

After a few more additional checks, I will make this available via `pip` as version 0.2.3.
